### ISSUE TITLE
netex_country_support-v1.1.xsd should be extended with Serbia (RS)

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#26]

**Comment by skinkie** [comment]
Fixed with https://github.com/NeTEx-CEN/NeTEx/commit/fdba840cfd250fbe5ae8d73e22ae1b75431c1f54

**Comment by nick-knowles** [comment]
This was fixed last year - should be closed

**Comment by skinkie** [comment]
@nick-knowles You did not fix the spelling mistake that I gave feedback on. In addition I also see an indentation error.

**Comment by ue71603** [comment]
fixed in master (rs). Rest we will find later, if still an issue.
